using System.Security.Cryptography;
using System.Security.Cryptography.X509Certificates;
using System.Text;
using FinPlat.Slt.Cli.Models;

namespace FinPlat.Slt.Cli.Generation;

/// <summary>
/// Generates all SLT infrastructure files from an SltManifest.
/// Handles Dockerfile, config, nginx, certs, and test class generation.
/// </summary>
public static class SltGenerator
{
    public static async Task<GenerationResult> GenerateAsync(SltManifest manifest, string repoRoot, GenerationOptions options)
    {
        var result = new GenerationResult();
        var sltDir = Path.Combine(repoRoot, ".slt");

        // 1. Generate manifest
        var manifestPath = Path.Combine(sltDir, "slt.json");
        manifest.SaveToFile(manifestPath);
        result.Generated.Add(manifestPath);

        // 2. Generate Dockerfile
        if (manifest.Docker.Dockerfile == null)
        {
            var dockerDir = Path.Combine(sltDir, "docker");
            Directory.CreateDirectory(dockerDir);

            var dockerfilePath = Path.Combine(dockerDir, "Dockerfile.slt");
            await WriteIfAllowedAsync(dockerfilePath, GenerateDockerfile(manifest, repoRoot), options, result);
        }

        // 3. Generate config.docker.json
        var configPath = Path.Combine(sltDir, "docker", "config.docker.json");
        await WriteIfAllowedAsync(configPath, GenerateDockerConfig(manifest), options, result);

        // 4. Generate nginx + certs (if HTTPS proxy needed)
        if (manifest.Infrastructure.UseHttpsProxy)
        {
            var nginxDir = Path.Combine(sltDir, "docker", "nginx");
            Directory.CreateDirectory(nginxDir);

            await WriteIfAllowedAsync(
                Path.Combine(nginxDir, "nginx.conf"),
                GenerateNginxConfig(), options, result);

            // Generate self-signed certificate
            await GenerateCertificateAsync(nginxDir, result);
        }

        // 5. Generate .gitignore for .slt
        var gitignorePath = Path.Combine(sltDir, ".gitignore");
        if (!File.Exists(gitignorePath))
        {
            await WriteIfAllowedAsync(gitignorePath, GenerateGitignore(), options, result);
        }

        // 6. Generate test project and classes
        if (manifest.Tests.ProjectPath != null)
        {
            var testProjDir = Path.Combine(repoRoot, Path.GetDirectoryName(manifest.Tests.ProjectPath)!);
            Directory.CreateDirectory(testProjDir);

            var csprojPath = Path.Combine(repoRoot, manifest.Tests.ProjectPath);
            if (!File.Exists(csprojPath))
            {
                await WriteIfAllowedAsync(csprojPath, GenerateTestCsproj(manifest), options, result);
            }

            // Generate test class for each worker
            var scenarioDir = Path.Combine(testProjDir, "Scenarios");
            Directory.CreateDirectory(scenarioDir);

            foreach (var worker in manifest.Workers)
            {
                var className = ToPascalCase(worker.Name.Replace("QueueWorkerV1", "").Replace("Worker", ""));
                var testPath = Path.Combine(testProjDir, $"{className}SltTests.cs");
                await WriteIfAllowedAsync(testPath,
                    GenerateTestClass(manifest, worker, className), options, result);

                // Generate scenario directory
                var workerScenarioDir = Path.Combine(scenarioDir, className);
                Directory.CreateDirectory(workerScenarioDir);

                var scenarioPath = Path.Combine(workerScenarioDir, "happy-path.json");
                if (!File.Exists(scenarioPath))
                {
                    await WriteIfAllowedAsync(scenarioPath, GenerateScenarioFile(), options, result);
                }
            }
        }

        return result;
    }

    private static string GenerateDockerfile(SltManifest manifest, string repoRoot)
    {
        var publishProject = manifest.Docker.PublishProject ?? manifest.ServiceProject;
        var sb = new StringBuilder();

        sb.AppendLine("# Auto-generated by dotnet-slt. Edit .slt/slt.json to customize.");
        sb.AppendLine("FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build");
        sb.AppendLine("WORKDIR /src");
        sb.AppendLine();
        sb.AppendLine("# Copy solution and restore");
        sb.AppendLine("COPY . .");
        sb.AppendLine($"RUN dotnet publish \"{publishProject}\" -c Release -o /app/publish --no-restore");
        sb.AppendLine();
        sb.AppendLine("FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS runtime");
        sb.AppendLine("WORKDIR /app");
        sb.AppendLine();
        sb.AppendLine("# Install CA certificate for Azurite HTTPS (token auth)");
        sb.AppendLine("COPY .slt/docker/nginx/azurite.crt /usr/local/share/ca-certificates/azurite-ca.crt");
        sb.AppendLine("RUN update-ca-certificates");
        sb.AppendLine();
        sb.AppendLine("COPY --from=build /app/publish .");
        sb.AppendLine();
        sb.AppendLine("# Copy SLT config");
        sb.AppendLine("COPY .slt/docker/config.docker.json /app/config.docker.json");
        sb.AppendLine();

        foreach (var (key, value) in manifest.Docker.EnvironmentVariables)
        {
            sb.AppendLine($"ENV {key}={value}");
        }

        sb.AppendLine($"EXPOSE {manifest.Docker.Port}");
        sb.AppendLine();
        var dllName = Path.GetFileNameWithoutExtension(publishProject) + ".dll";
        sb.AppendLine($"ENTRYPOINT [\"dotnet\", \"{dllName}\"]");

        return sb.ToString();
    }

    private static string GenerateDockerConfig(SltManifest manifest)
    {
        var sb = new StringBuilder();
        sb.AppendLine("{");
        sb.AppendLine("  \"Environment\": \"docker\",");

        // Queue worker configuration
        if (manifest.Workers.Count > 0)
        {
            sb.AppendLine("  \"AzureQueueWorkerConfiguration\": [");
            for (int i = 0; i < manifest.Workers.Count; i++)
            {
                var w = manifest.Workers[i];
                var comma = i < manifest.Workers.Count - 1 ? "," : "";
                sb.AppendLine("    {");
                sb.AppendLine($"      \"Name\": \"{w.Name}\",");
                sb.AppendLine("      \"DeadLetterWorkerInstances\": 0,");
                sb.AppendLine("      \"TestDeadLetterWorkerInstances\": 0,");
                sb.AppendLine("      \"TestWorkerInstances\": 0,");
                sb.AppendLine("      \"WorkerInstances\": 1");
                sb.AppendLine($"    }}{comma}");
            }
            sb.AppendLine("  ],");
        }

        // External API URIs (point to WireMock)
        foreach (var api in manifest.ExternalApis)
        {
            sb.AppendLine($"  \"{api.ConfigKey}\": \"http://mock-services:8080{api.BasePath}\",");
        }

        // Storage configuration
        sb.AppendLine("  \"StorageAccountConfiguration\": [");
        sb.AppendLine("    { \"Name\": \"devstoreaccount1\" }");
        sb.AppendLine("  ],");
        sb.AppendLine("  \"StorageAccountEndpointSuffix\": \"azurite.local\",");

        // Table configuration
        if (manifest.Infrastructure.Tables.Count > 0)
        {
            var tableName = manifest.Infrastructure.Tables[0];
            sb.AppendLine("  \"TableIndexAzureTableKeyValueStoreConfiguration\": [");
            sb.AppendLine("    {");
            sb.AppendLine("      \"AccountName\": \"devstoreaccount1\",");
            sb.AppendLine("      \"EndpointSuffix\": \"azurite.local\",");
            sb.AppendLine($"      \"TableName\": \"{tableName}\"");
            sb.AppendLine("    }");
            sb.AppendLine("  ],");
        }

        sb.AppendLine("  \"UseWorkloadIdentity\": true,");
        sb.AppendLine("  \"OpenTelemetryConsoleEnabled\": true,");
        sb.AppendLine("  \"GenevaCounterProviderEnabled\": false,");
        sb.AppendLine("  \"KeyVaultMonitorEnabled\": false");
        sb.AppendLine("}");

        return sb.ToString();
    }

    private static string GenerateNginxConfig()
    {
        return """
            # Auto-generated by dotnet-slt
            events { worker_connections 64; }
            http {
                upstream azurite_blob { server azurite:10000; }
                upstream azurite_queue { server azurite:10001; }
                upstream azurite_table { server azurite:10002; }

                server {
                    listen 443 ssl;
                    server_name *.azurite.local azurite.local;
                    ssl_certificate /etc/nginx/certs/azurite.crt;
                    ssl_certificate_key /etc/nginx/certs/azurite.key;

                    location / {
                        # Route based on Azure Storage URL pattern
                        proxy_pass http://azurite_blob;
                        proxy_set_header Host $host;
                        proxy_set_header X-Real-IP $remote_addr;
                    }
                }

                server {
                    listen 10001 ssl;
                    server_name *.azurite.local;
                    ssl_certificate /etc/nginx/certs/azurite.crt;
                    ssl_certificate_key /etc/nginx/certs/azurite.key;
                    location / { proxy_pass http://azurite_queue; proxy_set_header Host $host; }
                }

                server {
                    listen 10002 ssl;
                    server_name *.azurite.local;
                    ssl_certificate /etc/nginx/certs/azurite.crt;
                    ssl_certificate_key /etc/nginx/certs/azurite.key;
                    location / { proxy_pass http://azurite_table; proxy_set_header Host $host; }
                }
            }
            """;
    }

    private static async Task GenerateCertificateAsync(string nginxDir, GenerationResult result)
    {
        var certPath = Path.Combine(nginxDir, "azurite.crt");
        var keyPath = Path.Combine(nginxDir, "azurite.key");

        if (File.Exists(certPath) && File.Exists(keyPath))
        {
            result.Skipped.Add(certPath);
            return;
        }

        // Generate self-signed certificate using .NET crypto
        using var rsa = RSA.Create(2048);
        var request = new CertificateRequest(
            "CN=*.azurite.local, O=SLT Testing, C=US",
            rsa, HashAlgorithmName.SHA256, RSASignaturePadding.Pkcs1);

        // Add SAN extension
        var sanBuilder = new SubjectAlternativeNameBuilder();
        sanBuilder.AddDnsName("*.azurite.local");
        sanBuilder.AddDnsName("azurite.local");
        sanBuilder.AddDnsName("localhost");
        request.CertificateExtensions.Add(sanBuilder.Build());
        request.CertificateExtensions.Add(
            new X509BasicConstraintsExtension(true, false, 0, true));

        using var cert = request.CreateSelfSigned(
            DateTimeOffset.UtcNow.AddDays(-1),
            DateTimeOffset.UtcNow.AddYears(5));

        // Export PEM format
        var certPem = cert.ExportCertificatePem();
        var keyPem = rsa.ExportRSAPrivateKeyPem();

        await File.WriteAllTextAsync(certPath, certPem);
        await File.WriteAllTextAsync(keyPath, keyPem);

        result.Generated.Add(certPath);
        result.Generated.Add(keyPath);
    }

    private static string GenerateTestCsproj(SltManifest manifest)
    {
        return $"""
            <Project Sdk="Microsoft.NET.Sdk">
              <PropertyGroup>
                <TargetFramework>net8.0</TargetFramework>
                <IsPackable>false</IsPackable>
                <Nullable>enable</Nullable>
                <ImplicitUsings>enable</ImplicitUsings>
              </PropertyGroup>

              <ItemGroup>
                <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.12.0" />
                <PackageReference Include="MSTest.TestAdapter" Version="3.7.3" />
                <PackageReference Include="MSTest.TestFramework" Version="3.7.3" />
              </ItemGroup>

              <ItemGroup>
                <ProjectReference Include="..\..\{Path.GetDirectoryName(manifest.ServiceProject)}\FinPlat.TestContainers.csproj" 
                                  Condition="Exists('..\..\{Path.GetDirectoryName(manifest.ServiceProject)}\FinPlat.TestContainers.csproj')" />
                <!-- Or use NuGet: <PackageReference Include="FinPlat.TestContainers" Version="*" /> -->
              </ItemGroup>

              <ItemGroup>
                <Content Include="Scenarios\**\*" CopyToOutputDirectory="PreserveNewest" />
              </ItemGroup>
            </Project>
            """;
    }

    private static string GenerateTestClass(SltManifest manifest, WorkerConfig worker, string className)
    {
        var ns = manifest.Tests.Namespace ?? $"{className}.SltTests";
        var queueName = worker.QueueName;

        var apiMocks = string.Join("\n", manifest.ExternalApis.Select(a =>
            $"                mock.OnAny(\"{a.BasePath}\", 200, \"\"\"{a.DefaultResponse}\"\"\");"));

        var wireBlobs = string.Join("\n", manifest.Infrastructure.BlobContainers.Select(b =>
            $"                    .Blob(\"{b}\")"));
        var wireTables = string.Join("\n", manifest.Infrastructure.Tables.Select(t =>
            $"                    .Table(\"{t}\")"));

        return $$"""
            using System.Text;
            using System.Text.Json;
            using System.Text.Json.Nodes;
            using FinPlat.TestContainers;
            using FinPlat.TestContainers.Builder;
            using Microsoft.VisualStudio.TestTools.UnitTesting;

            namespace {{ns}};

            /// <summary>
            /// SLT tests for {{worker.Name}}.
            /// Auto-generated by dotnet-slt. Customize scenarios and assertions as needed.
            /// </summary>
            [TestClass]
            [TestCategory("SLT")]
            public class {{className}}SltTests
            {
                private static TestEnvironment _env = null!;

                [ClassInitialize]
                public static async Task ClassInit(TestContext _)
                {
                    var sltContext = GetSltContext();
                    var cert = new CertificateMaterial(
                        await File.ReadAllTextAsync(Path.Combine(sltContext, "docker", "nginx", "azurite.crt")),
                        await File.ReadAllTextAsync(Path.Combine(sltContext, "docker", "nginx", "azurite.key")));

                    _env = await new TestEnvironmentBuilder()
                        .AddAzurite(opts =>
                        {
                            opts.UseTokenAuth = true;
                            opts.ExternalCertificate = cert;
                        })
                        .AddMockApi("services", mock =>
                        {
            {{apiMocks}}
                            mock.OnUnmatched(200, "{}");
                        })
                        .AddApplication("{{manifest.ServiceName}}", app =>
                        {
                            app.FromDockerfile("docker/Dockerfile.slt", contextPath: sltContext);
                            app.WithEnv("WorkerNames", "{{worker.Name}}");
                            app.WithEnv("Logging__LogLevel__Default", "Information");
                        })
                        .Wire("{{manifest.ServiceName}}", wire =>
                        {
                            wire.Queue("{{queueName}}")
            {{wireBlobs}}
            {{wireTables}}
                                .UseTokenAuth()
                                .MockApi("services", "CollectorUri");
                        })
                        .BuildAsync();
                }

                [ClassCleanup]
                public static async Task ClassCleanup()
                {
                    if (_env != null) await _env.DisposeAsync();
                }

                [TestInitialize]
                public async Task TestInit()
                {
                    await _env.MockApi("services").ResetRequestLogAsync();
                }

                [TestMethod]
                public async Task HappyPath_MessageProcessedSuccessfully()
                {
                    // Arrange — load scenario fixture
                    var messageJson = await ReadScenarioAsync("happy-path.json");

                    // Act — send to queue
                    await _env.Queue("{{queueName}}").SendAsync(WrapInEventEntity(messageJson));
                    await Task.Delay(TimeSpan.FromSeconds(15));

                    // Assert — message was dequeued
                    var queueCount = await _env.Queue("{{queueName}}").GetMessageCountAsync();
                    Assert.AreEqual(0, queueCount, "Message should be dequeued from main queue");
                }

                [TestMethod]
                public async Task MalformedMessage_HandledGracefully()
                {
                    // Act — send empty JSON
                    await _env.Queue("{{queueName}}").SendAsync(WrapInEventEntity("{}"));
                    await Task.Delay(TimeSpan.FromSeconds(15));

                    // Assert — worker didn't crash (message removed from queue)
                    var queueCount = await _env.Queue("{{queueName}}").GetMessageCountAsync();
                    Assert.AreEqual(0, queueCount);
                }

                [TestMethod]
                public async Task WorkerRemainsHealthy_AfterProcessing()
                {
                    // Send first message
                    var msg = await ReadScenarioAsync("happy-path.json");
                    await _env.Queue("{{queueName}}").SendAsync(WrapInEventEntity(msg));
                    await Task.Delay(TimeSpan.FromSeconds(15));

                    // Send second to prove worker is still alive
                    await _env.Queue("{{queueName}}").SendAsync(WrapInEventEntity(msg));
                    await Task.Delay(TimeSpan.FromSeconds(15));

                    var queueCount = await _env.Queue("{{queueName}}").GetMessageCountAsync();
                    Assert.AreEqual(0, queueCount, "Worker should still be processing after first message");
                }

                #region Helpers
                private static string WrapInEventEntity(string eventJson)
                {
                    var envelope = new JsonObject
                    {
                        ["Event"] = JsonNode.Parse(eventJson),
                        ["EventType"] = "OrderCreation",
                        ["Properties"] = new JsonObject
                        {
                            ["EventHubMessageId"] = Guid.NewGuid().ToString(),
                            ["EventHubMessageQueueDate"] = DateTime.UtcNow.ToString("o")
                        }
                    };
                    return Convert.ToBase64String(Encoding.UTF8.GetBytes(envelope.ToJsonString()));
                }

                private static async Task<string> ReadScenarioAsync(string fileName)
                {
                    var path = Path.Combine(AppContext.BaseDirectory, "Scenarios", "{{className}}", fileName);
                    return await File.ReadAllTextAsync(path);
                }

                private static string GetSltContext()
                {
                    var dir = new DirectoryInfo(AppContext.BaseDirectory);
                    while (dir != null && !Directory.Exists(Path.Combine(dir.FullName, ".slt")))
                        dir = dir.Parent;
                    return dir != null ? Path.Combine(dir.FullName, ".slt")
                        : throw new InvalidOperationException("Cannot find .slt directory");
                }
                #endregion
            }
            """;
    }

    private static string GenerateScenarioFile()
    {
        return """
            {
              "_comment": "Replace with your actual test message payload",
              "id": "SLT-TEST-001",
              "state": "closed",
              "summary": {
                "purchaseRecordId": "SLT-TEST-001",
                "product": {
                  "productId": "TEST-PRODUCT-001"
                }
              }
            }
            """;
    }

    private static string GenerateGitignore()
    {
        return """
            # Generated at runtime — do not commit
            .generated/
            .certs/
            """;
    }

    private static async Task WriteIfAllowedAsync(
        string path, string content, GenerationOptions options, GenerationResult result)
    {
        if (options.DryRun)
        {
            result.Planned.Add(path);
            return;
        }

        if (File.Exists(path) && !options.Overwrite)
        {
            result.Skipped.Add(path);
            return;
        }

        Directory.CreateDirectory(Path.GetDirectoryName(path)!);
        await File.WriteAllTextAsync(path, content);
        result.Generated.Add(path);
    }

    private static string ToPascalCase(string name)
    {
        return string.Concat(
            name.Split(['-', '_', '.'], StringSplitOptions.RemoveEmptyEntries)
                .Select(w => char.ToUpperInvariant(w[0]) + w[1..]));
    }
}

public class GenerationOptions
{
    public bool DryRun { get; set; }
    public bool Overwrite { get; set; }
    public bool Interactive { get; set; }
}

public class GenerationResult
{
    public List<string> Generated { get; } = [];
    public List<string> Skipped { get; } = [];
    public List<string> Planned { get; } = [];
}
