using System.Security.Cryptography;
using System.Security.Cryptography.X509Certificates;
using System.Text;
using System.Text.Json;
using FinPlat.Slt.Cli.Models;

namespace FinPlat.Slt.Cli.Generation;

/// <summary>
/// Generates SLT files purely from manifest values.
/// Zero service-specific or collector-specific knowledge.
/// Every decision is driven by slt.json fields.
/// </summary>
public static class SltGenerator
{
    public static async Task<GenerationResult> GenerateAsync(SltManifest manifest, string repoRoot, GenerationOptions options)
    {
        var result = new GenerationResult();
        var sltDir = Path.Combine(repoRoot, ".slt");

        // 1. Save manifest
        var manifestPath = Path.Combine(sltDir, "slt.json");
        manifest.SaveToFile(manifestPath);
        result.Generated.Add(manifestPath);

        // 2. Docker infrastructure
        var dockerDir = Path.Combine(sltDir, "docker");
        Directory.CreateDirectory(dockerDir);

        if (manifest.Docker.Dockerfile == null)
        {
            await WriteIfAllowedAsync(
                Path.Combine(dockerDir, "Dockerfile.slt"),
                GenerateDockerfile(manifest), options, result);
        }

        await WriteIfAllowedAsync(
            Path.Combine(dockerDir, "config.docker.json"),
            GenerateDockerConfig(manifest), options, result);

        // 3. Nginx proxy (if needed)
        if (manifest.Infrastructure.UseHttpsProxy)
        {
            var nginxDir = Path.Combine(dockerDir, "nginx");
            Directory.CreateDirectory(nginxDir);

            await WriteIfAllowedAsync(Path.Combine(nginxDir, "nginx.conf"),
                GenerateNginxConfig(manifest), options, result);
            await WriteIfAllowedAsync(Path.Combine(nginxDir, "Dockerfile"),
                GenerateNginxDockerfile(), options, result);
            await GenerateCertificateAsync(nginxDir, manifest, result);
        }

        // 4. Publish script + gitignore
        await WriteIfAllowedAsync(Path.Combine(sltDir, "publish.ps1"),
            GeneratePublishScript(manifest), options, result);
        await WriteIfAllowedAsync(Path.Combine(sltDir, ".gitignore"),
            GenerateGitignore(), options, result);

        // 5. Test project
        if (manifest.Tests.ProjectPath != null)
        {
            var testProjDir = Path.Combine(repoRoot, Path.GetDirectoryName(manifest.Tests.ProjectPath)!);
            Directory.CreateDirectory(testProjDir);

            var csprojPath = Path.Combine(repoRoot, manifest.Tests.ProjectPath);
            if (!File.Exists(csprojPath))
                await WriteIfAllowedAsync(csprojPath, GenerateTestCsproj(manifest, repoRoot), options, result);

            var scenarioDir = Path.Combine(testProjDir, "Scenarios");
            Directory.CreateDirectory(scenarioDir);

            foreach (var worker in manifest.Workers)
            {
                var className = DeriveClassName(worker.Name);
                await WriteIfAllowedAsync(
                    Path.Combine(testProjDir, $"{className}SltTests.cs"),
                    GenerateTestClass(manifest, worker, className), options, result);

                // Create empty scenario directory — user provides their own fixture JSON
                var workerScenarioDir = Path.Combine(scenarioDir, className);
                Directory.CreateDirectory(workerScenarioDir);
            }
        }

        return result;
    }

    #region Dockerfile — driven by manifest.Docker.*

    private static string GenerateDockerfile(SltManifest manifest)
    {
        var entryDll = manifest.Docker.EntryDll
            ?? Path.GetFileNameWithoutExtension(manifest.ServiceProject) + ".dll";
        var certDest = manifest.Docker.CertInstall.CertDestination;
        var certCmd = manifest.Docker.CertInstall.UpdateCommand;
        var configTarget = manifest.Docker.ConfigTargetPath;

        var sb = new StringBuilder();
        sb.AppendLine($"# SLT Dockerfile — generated by dotnet-slt from .slt/slt.json");
        sb.AppendLine($"# Usage: docker build -f .slt/docker/Dockerfile.slt -t {manifest.ServiceName.ToLowerInvariant()}-slt .slt/");
        sb.AppendLine($"FROM {manifest.Docker.BaseImage}");
        sb.AppendLine();
        sb.AppendLine("WORKDIR /app");
        sb.AppendLine();
        sb.AppendLine("# Install CA certificate for HTTPS proxy");
        sb.AppendLine($"COPY docker/nginx/azurite.crt {certDest}");
        sb.AppendLine($"RUN {certCmd}");
        sb.AppendLine();
        sb.AppendLine("# Copy pre-published application");
        sb.AppendLine("COPY publish/ .");
        sb.AppendLine();
        sb.AppendLine("# Inject SLT config");
        sb.AppendLine($"COPY docker/config.docker.json {configTarget}");
        sb.AppendLine();

        // Static env vars from manifest
        foreach (var (key, value) in manifest.Docker.EnvironmentVariables)
            sb.AppendLine($"ENV {key}={value}");

        // Workload identity env vars (if enabled)
        if (manifest.Docker.UseWorkloadIdentity)
        {
            sb.AppendLine("# Workload identity simulation");
            sb.AppendLine("ENV AZURE_CLIENT_ID=00000000-0000-0000-0000-000000000000");
            sb.AppendLine("ENV AZURE_TENANT_ID=00000000-0000-0000-0000-000000000000");
            sb.AppendLine("ENV AZURE_CLIENT_SECRET=dummy-secret-for-slt");
            sb.AppendLine("ENV AZURE_FEDERATED_TOKEN_FILE=/app/federated-token.txt");
            sb.AppendLine("RUN echo \"dummy-federated-token\" > /app/federated-token.txt");
        }

        sb.AppendLine();
        sb.AppendLine($"ENTRYPOINT [\"dotnet\", \"{entryDll}\"]");
        return sb.ToString();
    }

    #endregion

    #region Docker config — driven by manifest.Workers + ExternalApis + Infrastructure

    private static string GenerateDockerConfig(SltManifest manifest)
    {
        var config = new Dictionary<string, object>();

        // Workers
        if (manifest.Workers.Count > 0)
        {
            config["AzureQueueWorkerConfiguration"] = manifest.Workers
                .Select(w => new Dictionary<string, object>
                {
                    ["Name"] = w.Name,
                    ["DeadLetterWorkerInstances"] = 0,
                    ["TestDeadLetterWorkerInstances"] = 0,
                    ["TestWorkerInstances"] = 0,
                    ["WorkerInstances"] = 1
                }).ToList();
        }

        // API URIs — each points to WireMock
        foreach (var api in manifest.ExternalApis)
        {
            config[api.ConfigKey] = $"http://mock-services:8080{api.BasePath}";
        }

        // Storage
        config["StorageAccountConfiguration"] = new[] { new { Name = "devstoreaccount1" } };
        config["StorageAccountEndpointSuffix"] = "azurite.local";

        // Tables
        if (manifest.Infrastructure.Tables.Count > 0)
        {
            var tableEntry = new { AccountName = "devstoreaccount1", EndpointSuffix = "azurite.local", TableName = manifest.Infrastructure.Tables[0] };
            config["TableIndexAzureTableKeyValueStoreConfiguration"] = new[] { tableEntry };
        }

        // Telemetry off
        config["OpenTelemetryConsoleEnabled"] = true;
        config["GenevaCounterProviderEnabled"] = false;
        config["KeyVaultMonitorEnabled"] = false;

        if (manifest.Docker.UseWorkloadIdentity)
            config["UseWorkloadIdentity"] = true;

        // Merge extra config sections from manifest
        if (manifest.Infrastructure.ExtraConfig != null)
        {
            foreach (var (key, value) in manifest.Infrastructure.ExtraConfig)
                config[key] = value;
        }

        return JsonSerializer.Serialize(config, new JsonSerializerOptions { WriteIndented = true });
    }

    #endregion

    #region Nginx — driven by manifest.Infrastructure.UseHttpsProxy + ProxyAuthEndpoint

    private static string GenerateNginxConfig(SltManifest manifest)
    {
        var sb = new StringBuilder();
        sb.AppendLine("# Auto-generated by dotnet-slt from .slt/slt.json");
        sb.AppendLine("worker_processes 1;");
        sb.AppendLine("events { worker_connections 128; }");
        sb.AppendLine();
        sb.AppendLine("http {");

        // Auth endpoint proxy (optional)
        if (manifest.Infrastructure.ProxyAuthEndpoint)
        {
            sb.AppendLine("    # Auth endpoint — intercepts login.microsoftonline.com");
            sb.AppendLine("    server {");
            sb.AppendLine("        listen 443 ssl;");
            sb.AppendLine("        server_name login.microsoftonline.com;");
            sb.AppendLine("        ssl_certificate /etc/nginx/certs/azurite.crt;");
            sb.AppendLine("        ssl_certificate_key /etc/nginx/certs/azurite.key;");
            sb.AppendLine("        location / {");
            sb.AppendLine("            proxy_pass http://wiremock:8080;");
            sb.AppendLine("            proxy_set_header Host $host;");
            sb.AppendLine("            proxy_set_header X-Forwarded-Proto https;");
            sb.AppendLine("        }");
            sb.AppendLine("    }");
            sb.AppendLine();
        }

        // Blob (10000)
        sb.AppendLine("    # Blob service");
        sb.AppendLine("    server {");
        sb.AppendLine("        listen 443 ssl;");
        sb.AppendLine("        server_name ~^(?<account>.+)\\.blob\\.azurite\\.local$;");
        sb.AppendLine("        ssl_certificate /etc/nginx/certs/azurite.crt;");
        sb.AppendLine("        ssl_certificate_key /etc/nginx/certs/azurite.key;");
        sb.AppendLine("        location / {");
        sb.AppendLine("            proxy_pass https://azurite:10000;");
        sb.AppendLine("            proxy_ssl_verify off;");
        sb.AppendLine("            proxy_set_header Host $host;");
        sb.AppendLine("            client_max_body_size 256m;");
        sb.AppendLine("            proxy_request_buffering off;");
        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine();

        // Queue (10001)
        sb.AppendLine("    # Queue service");
        sb.AppendLine("    server {");
        sb.AppendLine("        listen 443 ssl;");
        sb.AppendLine("        server_name ~^(?<account>.+)\\.queue\\.azurite\\.local$;");
        sb.AppendLine("        ssl_certificate /etc/nginx/certs/azurite.crt;");
        sb.AppendLine("        ssl_certificate_key /etc/nginx/certs/azurite.key;");
        sb.AppendLine("        location / {");
        sb.AppendLine("            proxy_pass https://azurite:10001;");
        sb.AppendLine("            proxy_ssl_verify off;");
        sb.AppendLine("            proxy_set_header Host $host;");
        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine();

        // Table (10002)
        sb.AppendLine("    # Table service");
        sb.AppendLine("    server {");
        sb.AppendLine("        listen 443 ssl;");
        sb.AppendLine("        server_name ~^(?<account>.+)\\.table\\.azurite\\.local$;");
        sb.AppendLine("        ssl_certificate /etc/nginx/certs/azurite.crt;");
        sb.AppendLine("        ssl_certificate_key /etc/nginx/certs/azurite.key;");
        sb.AppendLine("        location / {");
        sb.AppendLine("            proxy_pass https://azurite:10002;");
        sb.AppendLine("            proxy_ssl_verify off;");
        sb.AppendLine("            proxy_set_header Host $host;");
        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        return sb.ToString();
    }

    private static string GenerateNginxDockerfile()
    {
        return """
            FROM nginx:alpine
            RUN mkdir -p /etc/nginx/certs
            COPY nginx.conf /etc/nginx/nginx.conf
            COPY azurite.crt /etc/nginx/certs/azurite.crt
            COPY azurite.key /etc/nginx/certs/azurite.key
            """;
    }

    #endregion

    #region Certificates

    private static async Task GenerateCertificateAsync(string nginxDir, SltManifest manifest, GenerationResult result)
    {
        var certPath = Path.Combine(nginxDir, "azurite.crt");
        var keyPath = Path.Combine(nginxDir, "azurite.key");

        if (File.Exists(certPath) && File.Exists(keyPath))
        {
            result.Skipped.Add(certPath);
            return;
        }

        using var rsa = RSA.Create(2048);
        var request = new CertificateRequest(
            "CN=*.azurite.local, O=SLT, C=US",
            rsa, HashAlgorithmName.SHA256, RSASignaturePadding.Pkcs1);

        var sanBuilder = new SubjectAlternativeNameBuilder();
        sanBuilder.AddDnsName("*.azurite.local");
        sanBuilder.AddDnsName("*.blob.azurite.local");
        sanBuilder.AddDnsName("*.queue.azurite.local");
        sanBuilder.AddDnsName("*.table.azurite.local");
        sanBuilder.AddDnsName("azurite.local");
        sanBuilder.AddDnsName("localhost");
        if (manifest.Infrastructure.ProxyAuthEndpoint)
            sanBuilder.AddDnsName("login.microsoftonline.com");

        request.CertificateExtensions.Add(sanBuilder.Build());
        request.CertificateExtensions.Add(new X509BasicConstraintsExtension(true, false, 0, true));

        using var cert = request.CreateSelfSigned(
            DateTimeOffset.UtcNow.AddDays(-1), DateTimeOffset.UtcNow.AddYears(5));

        await File.WriteAllTextAsync(certPath, cert.ExportCertificatePem());
        await File.WriteAllTextAsync(keyPath, rsa.ExportRSAPrivateKeyPem());

        result.Generated.Add(certPath);
        result.Generated.Add(keyPath);
    }

    #endregion

    #region Test class — driven by manifest.ExternalApis + MessageEnvelope + Tests.*

    private static string GenerateTestClass(SltManifest manifest, WorkerConfig worker, string className)
    {
        var ns = manifest.Tests.Namespace ?? $"{manifest.ServiceName}.SltTests";
        var queueName = worker.QueueName;
        var timeout = manifest.Tests.ProcessingTimeoutSeconds;
        var pollInterval = manifest.Tests.PollingIntervalSeconds;

        // Build mock setup from ExternalApis — purely driven by manifest
        var mockLines = new StringBuilder();
        foreach (var api in manifest.ExternalApis)
        {
            var methodCall = api.Method.ToUpperInvariant() switch
            {
                "POST" => $"mock.OnPost(\"{api.BasePath}\", {api.DefaultStatusCode}, \"\"\"{api.DefaultResponse}\"\"\");",
                "GET" => $"mock.OnGet(\"{api.BasePath}\", {api.DefaultStatusCode}, \"\"\"{api.DefaultResponse}\"\"\");",
                _ => $"mock.OnAny(\"{api.BasePath}\", {api.DefaultStatusCode}, \"\"\"{api.DefaultResponse}\"\"\");"
            };
            mockLines.AppendLine($"                {methodCall}");

            // Additional routes
            if (api.AdditionalRoutes != null)
            {
                foreach (var route in api.AdditionalRoutes)
                {
                    var routeCall = route.Method.ToUpperInvariant() switch
                    {
                        "POST" => $"mock.OnPost(\"{route.Path}\", {route.StatusCode}, \"\"\"{route.Response}\"\"\");",
                        "GET" => $"mock.OnGet(\"{route.Path}\", {route.StatusCode}, \"\"\"{route.Response}\"\"\");",
                        _ => $"mock.OnAny(\"{route.Path}\", {route.StatusCode}, \"\"\"{route.Response}\"\"\");"
                    };
                    mockLines.AppendLine($"                {routeCall}");
                }
            }
        }
        mockLines.AppendLine("                mock.OnUnmatched(200, \"\"\"[]\"\"\");");

        // Build wire setup from manifest.Infrastructure
        var wireLines = new StringBuilder();
        wireLines.Append($"                wire.Queue(\"{queueName}\")");
        foreach (var table in manifest.Infrastructure.Tables)
            wireLines.Append($"\n                    .Table(\"{table}\")");
        foreach (var blob in manifest.Infrastructure.BlobContainers)
            wireLines.Append($"\n                    .Blob(\"{blob}\")");
        if (manifest.Infrastructure.UseTokenAuth)
            wireLines.Append("\n                    .UseTokenAuth()");
        // Wire the first API (user can customize)
        if (manifest.ExternalApis.Count > 0)
            wireLines.Append($"\n                    .MockApi(\"services\", \"{manifest.ExternalApis[0].ConfigKey}\")");
        wireLines.Append(";");

        // Message envelope helper — driven by manifest.MessageEnvelope
        var envelopeHelper = GenerateEnvelopeHelper(manifest.MessageEnvelope);

        return $$"""
            using System.Text;
            using System.Text.Json;
            using System.Text.Json.Nodes;
            using FinPlat.TestContainers;
            using FinPlat.TestContainers.Builder;
            using FinPlat.TestContainers.Config;
            using FinPlat.TestContainers.Containers;
            using Microsoft.VisualStudio.TestTools.UnitTesting;

            namespace {{ns}};

            // ┌──────────────────────────────────────────────────────────────────────────────┐
            // │  SLT Test for: {{worker.Name}}
            // │  Generated by: dotnet-slt init
            // │                                                                              │
            // │  HOW TO USE:                                                                 │
            // │  1. Add your fixture JSON to: Scenarios/{{className}}/happy-path.json        │
            // │  2. Customize mock responses below to match your scenario                    │
            // │  3. Add assertions for your expected behavior                                │
            // │                                                                              │
            // │  AVAILABLE ASSERTIONS:                                                       │
            // │  ─────────────────────                                                       │
            // │  Queue:                                                                      │
            // │    await _env.Queue("name").GetMessageCountAsync();                          │
            // │    await _env.Queue("name").IsEmptyAsync();                                  │
            // │    await _env.Queue("name").PeekAllAsync();        // peek without dequeue   │
            // │    await _env.DeadLetterQueue("name").GetMessageCountAsync(); // check DLQ   │
            // │    await _env.WaitForIdleAsync(timeout);           // wait all queues empty  │
            // │                                                                              │
            // │  Mock API Verification:                                                      │
            // │    await _env.MockApi("services").VerifyAsync("/path", Times.AtLeastOnce);   │
            // │    await _env.MockApi("services").VerifyAsync("/path", Times.Never);         │
            // │    await _env.MockApi("services").VerifyAsync("/path", Times.Exactly(2));    │
            // │    await _env.MockApi("services").AssertNotCalled("/path");                  │
            // │    var calls = await _env.MockApi("services").GetCallsAsync("/path");        │
            // │    var bodies = await _env.MockApi("services")                               │
            // │        .GetRequestBodiesAsAsync<MyDto>("/path");                             │
            // │    calls[0].BodyContains("expectedText");                                   │
            // │    calls[0].BodyAs<MyDto>();  // deserialize request body                    │
            // │    calls[0].JsonPathValue<string>("$.field");                                │
            // │                                                                              │
            // │  Table Storage:                                                              │
            // │    await _env.Table("name").CountAsync();                                    │
            // │    await _env.Table("name").ExistsAsync("pk", "rk");                        │
            // │    await _env.Table("name").QueryAsync("PartitionKey eq 'x'");              │
            // │                                                                              │
            // │  Blob Storage:                                                               │
            // │    await _env.Blob("container").DownloadAsAsync<MyDto>("blobName");          │
            // │    await _env.Blob("container").DownloadAsJsonAsync("blobName");             │
            // │                                                                              │
            // │  MOCK SETUP OPTIONS:                                                         │
            // │  ──────────────────                                                          │
            // │    mock.OnPost("/path", 200, "{\"response\": \"ok\"}");                      │
            // │    mock.OnGet("/path", 200, "[{\"id\":\"1\"}]");                             │
            // │    mock.OnAny("/path", 200, body);   // matches any HTTP method              │
            // │    mock.OnUnmatched(200, "[]");      // catch-all for unmatched routes        │
            // │                                                                              │
            // │  Fluent Setup (dynamic per-test):                                            │
            // │    await _env.MockApi("services").SetupAsync(s => s                          │
            // │        .OnPost("/path").Returns(201, "{\"id\":\"new\"}"));                    │
            // │    await _env.MockApi("services").SetupAsync(s => s                          │
            // │        .OnGet("/path").When(req => req.Url.Contains("filter"))               │
            // │        .Returns(200, "{\"filtered\": true}"));                               │
            // │    await _env.MockApi("services").SetupAsync(s => s                          │
            // │        .OnPost("/path").ReturnsSequence(                                     │
            // │            (200, "{\"attempt\":1}"),                                         │
            // │            (500, "{\"error\":\"retry\"}"),                                   │
            // │            (200, "{\"attempt\":2}")));                                       │
            // │                                                                              │
            // │  ENVIRONMENT HELPERS:                                                        │
            // │  ────────────────────                                                        │
            // │    await _env.WaitForIdleAsync(TimeSpan.FromSeconds(60)); // wait all queues │
            // │    await _env.ResetAsync();   // clear all queues + tables + request logs    │
            // │    await _env.MockApi("services").ResetRequestLogAsync(); // clear call log  │
            // │    await _env.Queue("name").ClearAsync();   // drain a specific queue        │
            // │    await _env.Table("name").ClearAsync();   // delete all rows               │
            // │                                                                              │
            // │  Times MATCHERS (like Moq):                                                  │
            // │    Times.Once           Times.Never          Times.AtLeastOnce               │
            // │    Times.Exactly(3)     Times.AtLeast(2)     Times.AtMost(5)                 │
            // │    Times.Between(1, 3)                                                       │
            // └──────────────────────────────────────────────────────────────────────────────┘

            [TestClass]
            [TestCategory("SLT")]
            public class {{className}}SltTests
            {
                private static TestEnvironment _env = null!;

                [ClassInitialize]
                public static async Task ClassInit(TestContext _)
                {
                    var sltContext = GetSltContext();
                    var cert = new CertificateMaterial(
                        await File.ReadAllTextAsync(Path.Combine(sltContext, "docker", "nginx", "azurite.crt")),
                        await File.ReadAllTextAsync(Path.Combine(sltContext, "docker", "nginx", "azurite.key")));

                    _env = await new TestEnvironmentBuilder()
                        .AddAzurite(opts =>
                        {
                            opts.UseTokenAuth = {{manifest.Infrastructure.UseTokenAuth.ToString().ToLower()}};
                            opts.ExternalCertificate = cert;
                        })
                        .AddMockApi("services", mock =>
                        {
            {{mockLines}}
                        })
                        .AddApplication("worker", app =>
                        {
                            app.FromDockerfile(
                                dockerfilePath: "docker/Dockerfile.slt",
                                contextPath: sltContext);
                            app.WithEnv("WorkerNames", "{{worker.Name}}");
                        })
                        .Wire("worker", wire =>
                        {
            {{wireLines}}
                        })
                        .BuildAsync();
                }

                [ClassCleanup]
                public static async Task ClassCleanup()
                {
                    if (_env != null) await _env.DisposeAsync();
                }

                [TestInitialize]
                public async Task TestInit()
                {
                    await _env.MockApi("services").ResetRequestLogAsync();
                }

                // ╔══════════════════════════════════════════════════════════════════╗
                // ║  YOUR TESTS GO HERE                                             ║
                // ║                                                                  ║
                // ║  Step 1: Create Scenarios/{{className}}/happy-path.json          ║
                // ║          with a real message payload for this worker.            ║
                // ║                                                                  ║
                // ║  Step 2: Write test methods below. Example patterns:             ║
                // ╚══════════════════════════════════════════════════════════════════╝

                [TestMethod]
                public async Task {{className}}_HappyPath_MessageProcessed()
                {
                    // TODO: Add your fixture at Scenarios/{{className}}/happy-path.json
                    var messageJson = await ReadScenarioFileAsync("happy-path.json");
                    await _env.Queue("{{queueName}}").SendAsync(WrapMessage(messageJson));

                    // Wait for all queues to drain (worker processes message)
                    await _env.WaitForIdleAsync(TimeSpan.FromSeconds({{timeout}}));

                    // Assert: no dead letters (message processed successfully)
                    Assert.IsTrue(
                        await _env.DeadLetterQueue("{{queueName}}").IsEmptyAsync(),
                        "No messages should land in dead-letter queue");

                    // Assert: mock API was called (uncomment and customize)
                    // await _env.MockApi("services").VerifyAsync("/your-endpoint", Times.AtLeastOnce);

                    // Assert: verify request body content (uncomment and customize)
                    // var calls = await _env.MockApi("services").GetCallsAsync("/your-endpoint");
                    // Assert.IsTrue(calls[0].BodyContains("expectedField"));

                    // Assert: table storage row created (uncomment and customize)
                    // Assert.IsTrue(await _env.Table("YourTable").ExistsAsync("partitionKey", "rowKey"));
                }

                [TestMethod]
                public async Task {{className}}_MalformedMessage_GoesToDeadLetter()
                {
                    await _env.Queue("{{queueName}}").SendAsync(WrapMessage("{}"));

                    await _env.WaitForIdleAsync(TimeSpan.FromSeconds({{timeout}}));

                    // Depending on your worker's error handling:
                    // Option A: message is gracefully discarded (queue empty, no DLQ)
                    Assert.IsTrue(await _env.Queue("{{queueName}}").IsEmptyAsync());

                    // Option B: message goes to dead-letter (uncomment if applicable)
                    // var dlqCount = await _env.DeadLetterQueue("{{queueName}}").GetMessageCountAsync();
                    // Assert.AreEqual(1, dlqCount, "Bad message should go to DLQ");
                }

                #region Helpers

            {{envelopeHelper}}

                private static async Task<string> ReadScenarioFileAsync(string fileName)
                {
                    var path = Path.Combine(AppContext.BaseDirectory, "Scenarios", "{{className}}", fileName);
                    return await File.ReadAllTextAsync(path);
                }

                private static string GetSltContext()
                {
                    var dir = new DirectoryInfo(AppContext.BaseDirectory);
                    while (dir != null && !Directory.Exists(Path.Combine(dir.FullName, ".slt")))
                        dir = dir.Parent;
                    return dir != null ? Path.Combine(dir.FullName, ".slt")
                        : throw new InvalidOperationException("Cannot find .slt directory. Run from repo root.");
                }

                #endregion
            }
            """;
    }

    /// <summary>
    /// Generates message wrapping helper based on manifest.MessageEnvelope config.
    /// No hardcoded EventEntityV1 or Collector knowledge.
    /// </summary>
    private static string GenerateEnvelopeHelper(MessageEnvelopeConfig envelope)
    {
        return envelope.Format switch
        {
            "base64-json" => $$"""
                    private static string WrapMessage(string eventJson)
                    {
                        var eventNode = JsonNode.Parse(eventJson);
                        var wrapper = new JsonObject
                        {
                            ["Event"] = eventNode,
                            ["EventType"] = "{{envelope.EventType}}",
                            ["Properties"] = new JsonObject
                            {
                                ["MessageId"] = Guid.NewGuid().ToString(),
                                ["EnqueuedTime"] = DateTime.UtcNow.ToString("o")
                            }
                        };
                        return Convert.ToBase64String(Encoding.UTF8.GetBytes(wrapper.ToJsonString()));
                    }
            """,
            "raw-json" => """
                    private static string WrapMessage(string eventJson) => eventJson;
            """,
            "base64-raw" => """
                    private static string WrapMessage(string eventJson)
                        => Convert.ToBase64String(Encoding.UTF8.GetBytes(eventJson));
            """,
            _ => """
                    private static string WrapMessage(string eventJson) => eventJson;
            """
        };
    }

    #endregion

    #region Test csproj

    private static string GenerateTestCsproj(SltManifest manifest, string repoRoot)
    {
        var hasTestProps = File.Exists(Path.Combine(repoRoot, "props", "Test.props"));
        var testPropsLine = hasTestProps
            ? "\n  <Import Project=\"$(ProjectDir)..\\..\\props\\Test.props\" />\n"
            : "";
        var ns = manifest.Tests.Namespace ?? $"{manifest.ServiceName}.SltTests";

        return $"""
            <Project Sdk="Microsoft.NET.Sdk">
            {testPropsLine}
              <PropertyGroup>
                <RootNamespace>{ns}</RootNamespace>
                <Nullable>enable</Nullable>
                <ImplicitUsings>enable</ImplicitUsings>
              </PropertyGroup>

              <ItemGroup>
                <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.4.0" />
                <PackageReference Include="MSTest.TestAdapter" Version="4.2.1" />
                <PackageReference Include="MSTest.TestFramework" Version="4.2.1" />
              </ItemGroup>

              <ItemGroup>
                <!-- Adjust path to FinPlat.TestContainers project or use NuGet package -->
                <ProjectReference Include="..\..\..\FinPlat.TestContainers\src\FinPlat.TestContainers\FinPlat.TestContainers.csproj" />
              </ItemGroup>

              <ItemGroup>
                <None Update="Scenarios\**\*.json">
                  <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
                </None>
              </ItemGroup>

            </Project>
            """;
    }

    #endregion

    #region Utility generators

    private static string GeneratePublishScript(SltManifest manifest)
    {
        var project = manifest.Docker.PublishProject ?? manifest.ServiceProject;
        return $$"""
            # Publish the service for SLT Docker build
            # Run from repo root: powershell .slt/publish.ps1
            param([string]$Configuration = "Release")
            $repoRoot = Split-Path -Parent $PSScriptRoot
            $output = Join-Path $PSScriptRoot "publish"
            Write-Host "Publishing {{manifest.ServiceName}}..."
            dotnet publish "$repoRoot/{{project.Replace('\\', '/')}}" -c $Configuration -o $output
            if ($LASTEXITCODE -eq 0) { Write-Host "Done: $output" -ForegroundColor Green }
            else { Write-Host "Failed" -ForegroundColor Red; exit 1 }
            """;
    }

    private static string GenerateGitignore()
    {
        return """
            # Pre-published binaries — rebuilt each run
            publish/
            """;
    }

    #endregion

    #region Shared helpers

    private static async Task WriteIfAllowedAsync(
        string path, string content, GenerationOptions options, GenerationResult result)
    {
        if (options.DryRun) { result.Planned.Add(path); return; }
        if (File.Exists(path) && !options.Overwrite) { result.Skipped.Add(path); return; }
        Directory.CreateDirectory(Path.GetDirectoryName(path)!);
        await File.WriteAllTextAsync(path, content);
        result.Generated.Add(path);
    }

    private static string DeriveClassName(string workerName)
    {
        return workerName
            .Replace("QueueWorkerV1", "")
            .Replace("QueueWorkerV2", "")
            .Replace("QueueWorkerV8", "")
            .Replace("QueueWorker", "")
            .Replace("Worker", "")
            .Replace("Organization", "Org");
    }

    #endregion
}

public class GenerationOptions
{
    public bool DryRun { get; set; }
    public bool Overwrite { get; set; }
    public bool Interactive { get; set; }
}

public class GenerationResult
{
    public List<string> Generated { get; } = [];
    public List<string> Skipped { get; } = [];
    public List<string> Planned { get; } = [];
}
