using System;
using System.IO;
using System.Text;
using FinPlat.TestContainers.Config;

namespace FinPlat.TestContainers.Containers;

/// <summary>
/// Generates a wrapper Dockerfile that layers <c>vsdbg</c> onto an existing
/// application image, leaving the base image's <c>ENTRYPOINT</c>, <c>CMD</c>,
/// <c>WORKDIR</c>, and <c>ENV</c> intact.
/// </summary>
/// <remarks>
/// The wrapper image runs as <c>root</c> by default because:
/// (a) it is only used for local debugging and is never deployed to production;
/// (b) <c>vsdbg</c> is invoked via <c>docker exec -u root</c> from the host, so
/// elevated privileges are required anyway; and
/// (c) restoring the base image's original user reliably requires inspecting
/// the base image config, which is more complexity than the spike warrants.
/// Set <see cref="DebuggerSupportOptions.RestoreUser"/> to opt into a specific
/// non-root user (e.g. "app") if the application requires it.
/// </remarks>
internal static class DebuggerImageBuilder
{
    /// <summary>
    /// Writes a wrapper Dockerfile to a fresh temp directory and returns the directory
    /// (build context) and Dockerfile path. Caller passes these to
    /// <c>ImageFromDockerfileBuilder</c> to produce the final debuggable image.
    /// </summary>
    /// <param name="baseImageTag">The fully qualified image tag to wrap (e.g. <c>my-app:abc123</c>).</param>
    /// <param name="options">vsdbg install configuration.</param>
    public static (string ContextPath, string DockerfilePath) WriteWrapperDockerfile(
        string baseImageTag, DebuggerSupportOptions options)
    {
        ArgumentNullException.ThrowIfNull(baseImageTag);
        ArgumentNullException.ThrowIfNull(options);

        var contextDir = Path.Combine(
            Path.GetTempPath(),
            "finplat-debug-wrap",
            Guid.NewGuid().ToString("N"));

        Directory.CreateDirectory(contextDir);

        var dockerfileContent = BuildWrapperDockerfileContent(baseImageTag, options);
        var dockerfilePath = Path.Combine(contextDir, "Dockerfile");
        File.WriteAllText(dockerfilePath, dockerfileContent);

        return (contextDir, "Dockerfile");
    }

    internal static string BuildWrapperDockerfileContent(string baseImageTag, DebuggerSupportOptions options)
    {
        var sb = new StringBuilder();

        sb.AppendLine($"# Auto-generated by FinPlat.TestContainers DebuggerImageBuilder. Do not edit.");
        sb.AppendLine($"# Layers vsdbg ({options.VsDbgVersion}) onto {baseImageTag} for in-container debugging.");
        sb.AppendLine($"FROM {baseImageTag}");
        sb.AppendLine();

        // Elevate so we can install packages and write to /vsdbg.
        sb.AppendLine("USER root");
        sb.AppendLine();

        switch (options.BaseImageType)
        {
            case DebuggerBaseImageType.DebianOrUbuntu:
                AppendDebianInstall(sb, options.VsDbgVersion);
                break;
            case DebuggerBaseImageType.Alpine:
                AppendAlpineInstall(sb, options.VsDbgVersion);
                break;
            default:
                throw new NotSupportedException(
                    $"Unsupported {nameof(DebuggerBaseImageType)} '{options.BaseImageType}'. " +
                    "Only DebianOrUbuntu and Alpine images are supported.");
        }

        // Sanity check: fail the build if vsdbg didn't land where we expect.
        sb.AppendLine();
        sb.AppendLine("RUN test -x /vsdbg/vsdbg || (echo 'vsdbg install failed' && exit 1)");

        if (!string.IsNullOrWhiteSpace(options.RestoreUser))
        {
            sb.AppendLine();
            sb.AppendLine($"# Restore the runtime user requested by DebuggerSupportOptions.RestoreUser.");
            sb.AppendLine($"USER {options.RestoreUser}");
        }

        return sb.ToString();
    }

    private static void AppendDebianInstall(StringBuilder sb, string vsDbgVersion)
    {
        sb.AppendLine("RUN apt-get update \\");
        sb.AppendLine(" && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \\");
        sb.AppendLine("      curl ca-certificates unzip procps \\");
        sb.AppendLine(" && rm -rf /var/lib/apt/lists/*");
        sb.AppendLine();
        sb.AppendLine($"RUN curl -sSL https://aka.ms/getvsdbgsh -o /tmp/getvsdbg.sh \\");
        sb.AppendLine($" && bash /tmp/getvsdbg.sh -v {EscapeForShell(vsDbgVersion)} -l /vsdbg \\");
        sb.AppendLine($" && rm /tmp/getvsdbg.sh");
    }

    private static void AppendAlpineInstall(StringBuilder sb, string vsDbgVersion)
    {
        sb.AppendLine("RUN apk add --no-cache curl ca-certificates bash unzip procps");
        sb.AppendLine();
        sb.AppendLine($"RUN curl -sSL https://aka.ms/getvsdbgsh -o /tmp/getvsdbg.sh \\");
        sb.AppendLine($" && bash /tmp/getvsdbg.sh -v {EscapeForShell(vsDbgVersion)} -l /vsdbg \\");
        sb.AppendLine($" && rm /tmp/getvsdbg.sh");
    }

    private static string EscapeForShell(string value)
    {
        // Allow alphanumerics, dot, dash, underscore; reject anything else to keep the install
        // line obviously safe (vsdbg version strings are like 'latest', 'vs2022', '17.12.20418').
        foreach (var c in value)
        {
            if (!(char.IsLetterOrDigit(c) || c == '.' || c == '-' || c == '_'))
            {
                throw new ArgumentException(
                    $"Invalid vsdbg version '{value}'. Only letters, digits, '.', '-', '_' are allowed.");
            }
        }
        return value;
    }
}
